site_name: deepset Cloud SDK
site_description: deepset Cloud SDK Documentation
site_url: https://deepset-ai.github.io/deepset-cloud-sdk/

# Repository
repo_name: deepset-ai/deepset-cloud-sdk
repo_url: https://github.com/deepset-ai/deepset-cloud-sdk
edit_uri: ""

theme:
  name: material
  favicon: _images/favicon.svg
  logo: _images/white-logo.svg
  features:
    - content.code.copy
  palette:
    primary: custom

plugins:
  - search
  - mermaid2
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike

extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js

extra_css:
  - _stylesheets/extra.css

# mkdocs uses the `docs` folder as root folder
nav:
  - Get Started: index.md
  - Upload Files: upload_files.md
  - Examples:
      - CLI: examples/cli/README.md
      - SDK: examples/sdk/README.md
  - API Docs: # autogenerated within the /docs/_pydoc folder
      - CLI: _pydoc/temp/cli.md
      - Synchronous SDK: _pydoc/temp/sync_client.md
      - Asynchronous SDK: _pydoc/temp/async_client.md
